edition = "2024"

hard_tabs = true

reorder_imports = true
reorder_modules = true

format_code_in_doc_comments = true
format_strings = true

merge_derives = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"

use_field_init_shorthand = true
